import {
    IntegrationAdapter,
    ProviderConfig,
    VismaConfig,
    SyncTimeEntry,
    SyncResult,
    TestResult,
} from "../types.js";

type FetchLike = (input: string, init?: RequestInit) => Promise<Response>;

function isVismaConfig(c: ProviderConfig): c is VismaConfig {
    return "clientId" in c && "targetApi" in c;
}

function getBaseUrl() {
    return process.env.VISMA_API_BASE_URL?.trim() || "https://api.visma.com";
}

function getTestPath() {
    return process.env.VISMA_TEST_ENDPOINT_PATH?.trim() || "/v2/shortcuts/hoursworked";
}

function getPayrollSyncPath() {
    return process.env.VISMA_PAYROLL_SYNC_ENDPOINT_PATH?.trim() || "/v2/shortcuts/hoursworked";
}

function getBookkeepingSyncPath() {
    return process.env.VISMA_BOOKKEEPING_SYNC_ENDPOINT_PATH?.trim() || "/v2/customerinvoicedrafts";
}

function buildHeaders(token: string): HeadersInit {
    return {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
        Accept: "application/json",
    };
}

function mapEntryToPayrollPayload(entry: SyncTimeEntry) {
    return {
        employeeId: entry.externalEmployeeId,
        date: entry.date,
        hoursWorked: entry.hours,
        description: entry.note ?? undefined,
        projectId: entry.projectId,
    };
}

function mapEntriesToBookkeepingDraft(entries: SyncTimeEntry[]) {
    return {
        note: "Generated by Fauke",
        rows: entries.map((entry) => ({
            text: entry.note || `${entry.projectName} (${entry.date})`,
            projectId: entry.projectId,
            quantity: entry.hours,
            unit: "h",
            date: entry.date,
            employeeId: entry.externalEmployeeId,
        })),
    };
}

async function parseErrorMessage(response: Response): Promise<string> {
    const text = await response.text().catch(() => "");
    if (!text) return `HTTP ${response.status}`;
    try {
        const parsed = JSON.parse(text) as Record<string, unknown>;
        if (typeof parsed.error === "string") return parsed.error;
        if (typeof parsed.message === "string") return parsed.message;
    } catch {
        // ignore json parse failure
    }
    return text;
}

export class VismaAdapter implements IntegrationAdapter {
    readonly provider = "visma" as const;
    private readonly fetchImpl: FetchLike;

    constructor(fetchImpl?: FetchLike) {
        this.fetchImpl = fetchImpl ?? (globalThis.fetch as FetchLike);
    }

    async testConnection(config: ProviderConfig): Promise<TestResult> {
        if (!isVismaConfig(config)) {
            return { success: false, message: "Invalid Visma configuration" };
        }
        if (!config.clientId || !config.clientSecret) {
            return { success: false, message: "Client ID and Client Secret are required" };
        }
        if (!config.accessToken) {
            return {
                success: false,
                message: "No access token — user needs to authorize via Visma identity server",
            };
        }

        const url = `${getBaseUrl()}${getTestPath()}`;
        const response = await this.fetchImpl(url, {
            method: "GET",
            headers: buildHeaders(config.accessToken),
        });

        if (!response.ok) {
            const details = await parseErrorMessage(response);
            return {
                success: false,
                message: `Visma connection failed (${response.status}): ${details}`,
            };
        }

        const apiLabel = config.targetApi === "payroll" ? "Visma Lön Smart (Payroll)" : "Visma eEkonomi (Bookkeeping)";
        return {
            success: true,
            message: `Connected to ${apiLabel}. Bearer token valid.`,
        };
    }

    async syncTimeEntries(config: ProviderConfig, entries: SyncTimeEntry[]): Promise<SyncResult> {
        if (!isVismaConfig(config)) {
            return { success: false, entriesSynced: 0, message: "Invalid Visma configuration" };
        }
        if (!config.accessToken) {
            return { success: false, entriesSynced: 0, message: "Missing access token" };
        }
        if (entries.length === 0) {
            return { success: true, entriesSynced: 0, message: "No entries to sync" };
        }

        const failedEntryIds: string[] = [];
        let synced = 0;

        if (config.targetApi === "payroll") {
            const endpoint = `${getBaseUrl()}${getPayrollSyncPath()}`;

            for (const entry of entries) {
                const payload = mapEntryToPayrollPayload(entry);
                const response = await this.fetchImpl(endpoint, {
                    method: "POST",
                    headers: buildHeaders(config.accessToken),
                    body: JSON.stringify(payload),
                });

                if (!response.ok) {
                    failedEntryIds.push(entry.projectId);
                    continue;
                }

                synced += 1;
            }
        } else {
            const endpoint = `${getBaseUrl()}${getBookkeepingSyncPath()}`;
            const payload = mapEntriesToBookkeepingDraft(entries);
            const response = await this.fetchImpl(endpoint, {
                method: "POST",
                headers: buildHeaders(config.accessToken),
                body: JSON.stringify(payload),
            });

            if (!response.ok) {
                const allIds = entries.map((e) => e.projectId);
                return {
                    success: false,
                    entriesSynced: 0,
                    message: `Synced 0/${entries.length} entries — ${entries.length} failed`,
                    failedEntryIds: allIds,
                };
            }

            synced = entries.length;
        }

        const allOk = failedEntryIds.length === 0;
        return {
            success: allOk,
            entriesSynced: synced,
            message: allOk
                ? `Synced ${synced} entries to Visma`
                : `Synced ${synced}/${entries.length} entries — ${failedEntryIds.length} failed`,
            failedEntryIds: failedEntryIds.length > 0 ? failedEntryIds : undefined,
        };
    }
}

export { mapEntryToPayrollPayload, mapEntriesToBookkeepingDraft };
